resource_types:
- name: repository-resource
  type: registry-image
  source:
    repository: cfje/repository-resource
    tag: latest

- name: glenn-github-release-resource
  type: registry-image
  source:
    repository: pcfmetrics/glenn-github-release-resource
    tag: latest

resources:
- name: java-release
  type: git
  source:
    uri: git@github.com:bosh-packages/java-release
    branch: maintain
    private_key: ((github_deployment_key))

- name: stemcell
  type: bosh-io-stemcell
  source:
    name: bosh-warden-boshlite-ubuntu-xenial-go_agent

jobs:
- name: build-8
  serial: true
  plan:
  - aggregate:
    - get: java-release
    - get: stemcell
      trigger: true
  - task: get_release
    file: java-release/ci/get_release.yml
    params:
      JAVA_VERSION: 8
  - task: build
    privileged: true
    file: java-release/ci/build.yml
    params:
      BLOBSTORE_ACCESS_KEY_ID: ((release_blobs_access_key_id))
      BLOBSTORE_SECRET_ACCESS_KEY: ((release_blobs_secret_access_key))
  - put: java-release
    params:
      rebase: true
      repository: java-release-out

- name: build-11
  serial: true
  plan:
  - aggregate:
    - get: java-release
    - get: stemcell
      trigger: true
  - task: get_release
    file: java-release/ci/get_release.yml
    params:
      JAVA_VERSION: 11
  - task: build
    privileged: true
    file: java-release/ci/build.yml
    params:
      BLOBSTORE_ACCESS_KEY_ID: ((release_blobs_access_key_id))
      BLOBSTORE_SECRET_ACCESS_KEY: ((release_blobs_secret_access_key))
  - put: java-release
    params:
      rebase: true
      repository: java-release-out